root/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from course.views import cmt_json, course_detail, course_list, history_courses, history_quizzes, save_cmt, save_student_course, search, subject_list, teacher_add_course, teacher_del_course, teacher_get_course_json, teacher_manage_course, teacher_modify_course, teacher_view_course
from quiz.views import get_list_score, question_bydocx_data, quiz_data, quiz_detail, quizzes_json, save_quiz, show_quizzes, subject_quizzes, teacher_add_question_bydocx, teacher_add_question_form, teacher_add_quiz, teacher_delete_quiz, teacher_get_quiz_data, teacher_get_subject, teacher_manage_score, teacher_save_question_form, teacher_save_quiz
from user.views import get_infor, login_view, logout_view, modify_account, student, teacher, teacher_get_infor, teacher_modify_account, teacher_view_profile, view_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('student/', include([
        path('', student, name='student_home'),
        path('search/', search, name='search'),
        path('major/<int:id>', subject_list, name='subject_list'),
        path('subject/<int:id>', course_list, name='course_list'),
        path('course/<int:id>', course_detail, name='course_detail'),
        path('course/<int:id>/save', save_student_course, name='save_student_course'),
        path('course/<int:id>/cmt', cmt_json, name='cmt_json'),
        path('course/<int:id>/save-cmt', save_cmt, name='save_cmt'),
        path('subject-quiz', subject_quizzes, name='subject_quizzes'),
        path('subject-quiz/<int:id>', show_quizzes, name='quizzes'),
        path('quiz/<int:id>', quiz_detail, name='quiz_detail'),
        path('quiz/<int:id>/data', quiz_data, name='quiz_data'),
        path('quiz/<int:id>/save', save_quiz, name='save_quiz'),
        path('history-course/', history_courses, name='history_courses'),
        path('history-quizzes/', history_quizzes, name='history_quizzes'),
        path('profile/', view_profile, name='view_profile'),
        path('profile/modify-account', modify_account, name='modify_account'),
        path('profile/get-infor', get_infor, name='get_infor'),

    ])),

    path('teacher/', include([
        path('', teacher, name='teacher_home'),
        path('manage-course/', teacher_manage_course, name="manage_course"),
        path('add-course/', teacher_add_course, name="add_course"),
        path('view-course/<int:id>', teacher_view_course, name="view_course"),
        path('view-course/<int:id>/cmt', cmt_json, name='cmt_json'),
        path('view-course/<int:id>/save-cmt', save_cmt, name='save_cmt'),
        path('modify-course/<int:id>', teacher_modify_course, name="modify_course"),
        path('modify-course/<int:id>/get-course', teacher_get_course_json, name="get_course_json"),
        path('delete-course/<int:id>', teacher_del_course, name="del_course"),
        path('manage-quiz/', teacher_get_subject, name="subject_quiz"),
        path('manage-quiz/<int:id>/data', quizzes_json, name="quizzes_json"),
        path('add-quiz/<int:id>/', teacher_add_quiz, name="add_quiz"),
        path('add-quiz/<int:id>/save', teacher_save_quiz, name="save_quiz"),
        path('add-question-form/<int:id>', teacher_add_question_form, name="add_question_manual"),
        path('add-question-form/<int:id>/save', teacher_save_question_form, name="save_question_manual"),
        path('add-question-bydocx/<int:id>', teacher_add_question_bydocx, name="add_question_bydocx"),
        path('add-question-bydocx/<int:id>/data', question_bydocx_data, name="get_question_bydocx"),
        path('delete-quiz/<int:id>/', teacher_delete_quiz, name="delete_quiz"),
        path('manage-score/', teacher_manage_score, name='manage_score'),
        path('manage-score/<int:id>/data', teacher_get_quiz_data, name='manage_score'),
        path('view-score/<int:id>', get_list_score, name="view_score"),
        path('profile/', teacher_view_profile, name="teacher_profile"),
        path('profile/get-infor', teacher_get_infor),
        path('profile/modify-account', teacher_modify_account),
    ])),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from user.models import Teacher, Student

# Create your models here.

class Major(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(default='', blank=True, null=True)

    def __str__(self):
        return self.name


class Subject(models.Model):
    major = models.ForeignKey(Major, on_delete=models.CASCADE, default='')
    name = models.CharField(max_length=100)
    description = models.TextField(default='', blank=True, null=True)

    def __str__(self):
        return self.name + " --- Thuộc ngành: " + self.major.name


class Course(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='courses')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='courses')
    name = models.CharField(max_length=100)
    description = models.TextField(default='', blank=True, null=True)
    body = models.TextField(default='', blank=True, null=True)
    pdf = models.FileField(upload_to='pdf', default='', blank=True, null=True)
    video = models.FileField(upload_to='video', default='', blank=True, null=True)
    powerpoint = models.FileField(upload_to='powerpoint', default='', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + ' --- ' + self.teacher.name


class Comment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    body = models.TextField(default='')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.course.name} --- {self.pk}"


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='history_study')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='history_study')
    created_at = models.DateTimeField(auto_now_add=True)

quiz/models.py
import random
from django.db import models
from course.models import Subject
from user.models import Student, Teacher

# Create your models here.

DIFF_CHOICES = {
    ('Dễ', 'Dễ'),
    ('Trung bình', 'Trung bình'),
    ('Khó', 'Khó')
}

RESULT_CHOICES = {
    ("Có", 'Có'),
    ("Không", 'Không')
}

class Quiz(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='quizzes')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    number_of_question = models.IntegerField(default=0)
    time = models.IntegerField(help_text="Thời gian làm bài")
    required_score_to_pass = models.IntegerField(help_text="Điểm cần đạt")
    difficulity = models.CharField(max_length=10, choices=DIFF_CHOICES)
    show_result = models.CharField(max_length=10, choices=RESULT_CHOICES, default="Có")
    docx = models.FileField(upload_to='quiz', default='', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"

    def search(self):
        return f"{self.name} - {self.subject.name}"        

    def get_question(self):
        questions = list(self.questions.all())
        random.shuffle(questions)
        return questions[:self.number_of_question]


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField(max_length=255)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        answers = list(self.answers.all()) # = return self.answer_set.all()
        random.shuffle(answers)
        return answers 


class Answer(models.Model):
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"


class StudentAnswer(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz_result')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_result')
    score = models.FloatField()

    def __str__(self):
        return f"{self.quiz.name} - {self.student.name}"

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

# Create your models here.


class Student(models.Model):
    gender_choice = (("Nữ", "Nữ"), ("Nam", "Nam"), ("Khác", "Khác"))
    student = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student')
    avatar = models.ImageField(upload_to='img', default='')
    name = models.CharField(max_length=50)
    school_year = models.CharField(max_length=100, default='')
    gender = models.CharField(max_length=20, choices=gender_choice)
    address = models.CharField(max_length=100, default='', blank=True, null=True)
    email = models.CharField(max_length=100, default='')
    phone = models.CharField(default='', max_length=15, blank=True, null=True)

    def __str__(self):
        return self.name


class Teacher(models.Model):
    gender_choice = (("Nữ", "Nữ"), ("Nam", "Nam"), ("Khác", "Khác"))
    teacher = models.OneToOneField(User, on_delete=models.CASCADE, related_name='teacher')
    major = models.ForeignKey("course.Major", on_delete=models.CASCADE, related_name='teacher')
    avatar = models.ImageField(upload_to='img', default='')
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=20, choices=gender_choice)
    email = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name + '  ---  Thuộc khoa: ' + self.major.name

templates/teacher/add-question-bydocx.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block add_question_bydocx %}
<div id="add-question">
    <form id="add-bydocx-form" action="{% url 'add_question_bydocx' quiz.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group text-right">
            <button 
                id="add-button" 
                type="submit" 
                class="btn btn-success"
            >
               <i class='bx bx-plus-circle' ></i>&nbsp;&nbsp;Tạo câu hỏi
            </button>
            <span class="mr-3 text-success" id="notify-infor"></span>
        </div>
        <div class="form-group row my-3">
            <label for="subjectName" class="col-sm-2 col-form-label"><strong>Tên bài quiz</strong></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="subjectName" id="subjectName" value="{{ quiz }}" readonly>
            </div>
        </div>
        <div class="form-group row my-3">
            <label for="{{ form.docx.id_for_label }}" class="col-sm-2 col-form-label"><strong>File bài quiz</strong></label>
            <div class="col-sm-10">
                {{ form.docx }}
            </div>
        </div>
    </form>
    <p><strong>Note:</strong> Xem hướng dẫn tạo file .docx hợp lệ tại <a href="{% static 'teacher/link/Hướng dẫn tạo file .docx hơp lệ.docx' %}">đây!</a></p>
    <div class="border-top border-primary my-4 w-100"></div>
    <div id="show-question">
        <h3 class="title-quiz fw-bold">{{ quiz }} - {{ subject }}</h3>
        <hr>
        <div id="question-detail" class="mt-3">
        </div>
    </div>
</div>
<script src="{% static 'teacher/js/add-ques-docx.js' %}"></script>
{% endblock %}

templates/teacher/add-question-form.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block add_question_form %}
<div id="add-question">
    <form id="add-manual-form">
        {% csrf_token %}
        <div class="form-group text-right">
            <button 
                id="add-button" 
                type="submit" 
                class="btn btn-success"
            >
               <i class='bx bx-plus-circle' ></i>&nbsp;&nbsp;Tạo câu hỏi
            </button>
            <span class="mr-3 text-success" id="notify-infor"></span>
        </div>
        <div class="form-group row my-3">
            <label for="subjectName" class="col-sm-2 col-form-label"><strong>Tên bài quiz</strong></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="subjectName" id="subjectName" value="{{ quiz }}" readonly>
            </div>
        </div>
        <div class="form-group row my-3">
            <label for="question" class="col-sm-2 col-form-label"><strong>Câu hỏi</strong></label>
            <div class="col-sm-10">
                <textarea class="form-control" id="question" name="question"></textarea>
            </div>
        </div>
        <div id="answer-box">
            <div class="form-group row my-3">
                <label for="answerA" class="col-sm-2 col-form-label"><strong>Đáp án A</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="answerA" id="answerA">
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="answerB" class="col-sm-2 col-form-label"><strong>Đáp án B</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="answerB" id="answerB">
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="answerC" class="col-sm-2 col-form-label"><strong>Đáp án C</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="answerC" id="answerC">
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="answerD" class="col-sm-2 col-form-label"><strong>Đáp án D</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="answerD" id="answerD">
                </div>
            </div>
        </div>
        <div class="form-group row my-3">
            <label for="correctAns" class="col-sm-2 col-form-label"><strong>Đáp án đúng</strong></label>
            <div class="col-sm-10">
                <select class="form-select" name="correctAns" id="correctAns">
                    <option value="A">A</option>
                    <option value="B">B</option>
                    <option value="C">C</option>
                    <option value="D">D</option>
                </select>
            </div>
        </div>
    </form>
    <div class="border-top border-primary my-4 w-100"></div>
    <div id="show-question">
        <h3 class="title-quiz fw-bold">{{ quiz }} - {{ subject }}</h3>
        <hr>
        <div id="question-detail" class="mt-3">
        </div>
    </div>
</div>
<script src="{% static 'teacher/js/add-ques-form.js' %}"></script>
{% endblock %}

templates/teacher/add_course.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block add_course %}

<form action="{% url 'add_course' %}" id="add-form" enctype="multipart/form-data"  method="POST" novalidate>
    {% csrf_token %}
    <div class="form-group text-right mt-2">
        <button id="add-button" type="submit" class="btn btn-success"><i class='bx bx-add-to-queue'></i>&nbsp;&nbsp;Tạo bài giảng</button>
        <span class="mr-3 text-success" id="notify-infor"></span>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.subject.id_for_label }}" class="col-sm-2 col-form-label"><strong>Môn học</strong></label>
        <div class="col-sm-10">
            {{ form.subject }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.name.id_for_label }}" class="col-sm-2 col-form-label"><strong>Tên bài giảng</strong></label>
        <div class="col-sm-10">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.description.id_for_label }}" class="col-sm-2 col-form-label"><strong>Mô tả</strong></label>
        <div class="col-sm-10">
            {{ form.description }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.body.id_for_label }}" class="col-sm-2 col-form-label"><strong>Nội dung</strong></label>
        <div class="col-sm-10">
            {{ form.body }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.pdf.id_for_label }}" class="col-sm-2 col-form-label"><strong>PDF</strong></label>
        <div class="col-sm-10">
            {{ form.pdf }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.video.id_for_label }}" class="col-sm-2 col-form-label"><strong>Video</strong></label>
        <div class="col-sm-10">
            {{ form.video }}
        </div>
    </div>
</form>
<script>
    const notify = document.getElementById('notify-infor');
    const addBtn = document.getElementById('add-button');

    tinymce.init({
        selector: '#id_body'
    });

</script>
{% endblock %}

templates/teacher/add_quiz.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block add_quiz %}
    <div id="add-quiz">
        <form id="add-quiz-form">
            {% csrf_token %}
            <div class="form-group text-right">
                <button 
                    id="add-button" 
                    type="submit" 
                    class="btn btn-success"
                    data-bs-toggle="modal"
                    data-bs-target="#createQuiz"
                >
                    <i class='bx bx-add-to-queue'></i>&nbsp;&nbsp;Tạo bài quiz
                </button>
                <span class="mr-3 text-success" id="notify-infor"></span>
            </div>
            <div class="form-group row my-3">
                <label for="subjectName" class="col-sm-2 col-form-label"><strong>Tên môn học</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="subjectName" id="subjectName" value="{{ subject }}" readonly>
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="quizName" class="col-sm-2 col-form-label"><strong>Tên bài quiz</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="quizName" id="quizName">
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="numberQuestion" class="col-sm-2 col-form-label"><strong>Số câu hỏi</strong></label>
                <div class="col-sm-10">
                    <input type="number" class="form-control" name="numberQuestion" id="numberQuestion">
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="time" class="col-sm-2 col-form-label"><strong>Thời gian</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="time" id="time">
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="requiredScore" class="col-sm-2 col-form-label"><strong>Điểm cần đạt</strong></label>
                <div class="col-sm-10">
                    <input type="number" step="0.01" class="form-control" name="requiredScore" id="requiredScore">
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="difficulity" class="col-sm-2 col-form-label"><strong>Độ khó</strong></label>
                <div class="col-sm-10">
                    <select class="form-select" name="difficulity" id="difficulity">
                        <option value="Dễ">Dễ</option>
                        <option value="Trung bình">Trung bình</option>
                        <option value="Khó">Khó</option>
                    </select>
                </div>
            </div>
            <div class="form-group row my-3">
                <label for="showResult" class="col-sm-2 col-form-label"><strong>Hiện kết quả</strong></label>
                <div class="col-sm-10">
                    <select class="form-select" name="showResult" id="showResult">
                        <option value="Có">Có</option>
                        <option value="Không">Không</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
    <div class="modal fade" id="createQuiz" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">TẠO CÂU HỎI</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center" id="modal-body-confirm">
                        <button id="create-manual-button" class="btn btn-primary btn-lg mx-3">Tạo thủ công</button>
                        <button id="create-bydocx-button" class="btn btn-primary btn-lg">Tạo bằng .docx</button>
                    </div>
                    <div class="modal-footer">
                        <!-- <button type="button" class="btn btn-success" data-bs-dismiss="modal">Không</button> -->
                    </div>
                </div>
            </div>
        </div>
    <script src="{% static 'teacher/js/create-quiz.js' %}"></script>

{% endblock %}

templates/teacher/manage_quiz.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block subject_quiz %}
    <div class="subject-quiz row">
        <div class="subject-list col-lg">
            {% for sub in subjects %}
            <div class="row">
                <button
                    type="submit"
                    class="col-10 btn btn-primary show-quiz-button btn-lg my-2"
                    data-pk="{{ sub.id }}"
                    data-quiz="{{ sub.quizzes.all }}"
                >
                {{ sub.name }}
                </button>
                <span class="arrow col-2 d-flex justify-content-center align-items-center">
                    <i id="{{ sub.id }}" class="arrow-icon bx bxs-right-arrow"></i>
                </span>
            </div>
            {% endfor %}
        </div>

        <div class="col-lg" id="quiz-box">
            <div id="add-quiz-btn"></div>
            <div id="quiz-list" class="mx-4"></div>
        </div>
    </div>
    <div class="modal fade" id="delQuizModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">XÓA BÀI QUIZ</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-score" id="modal-quiz-confirm">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-bs-dismiss="modal">Không</button>
                    <button type="button" id="del-button" class="btn btn-danger" data-bs-dismiss="modal">Có</button>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'teacher/js/manage-quiz.js' %}"></script>
{% endblock %}

templates/teacher/modify_course.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block modify_course %}

<form action="{% url 'modify_course' course_id %}" id="modify-form" enctype="multipart/form-data"  method="POST">
    {% csrf_token %}
    <div class="form-group text-right mt-2">
        <button type="submit" class="btn btn-success"><i class='bx bxs-save'></i>&nbsp;&nbsp;Lưu</button>
        <span class="mr-3 text-success" id="notify-infor"></span>
    </div>
    <!-- <div class="form-group row my-3">
        <label for="{{ form.subject.id_for_label }}" class="col-sm-2 col-form-label"><strong>Môn học</strong></label>
        <div class="col-sm-10">
            {{ form.subject }}
        </div>
    </div> -->
    <div class="form-group row my-3">
        <label for="{{ form.name.id_for_label }}" class="col-sm-2 col-form-label"><strong>Tên bài giảng</strong></label>
        <div class="col-sm-10">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.description.id_for_label }}" class="col-sm-2 col-form-label"><strong>Mô tả</strong></label>
        <div class="col-sm-10">
            {{ form.description }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.body.id_for_label }}" class="col-sm-2 col-form-label"><strong>Nội dung</strong></label>
        <div class="col-sm-10">
            {{ form.body }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.pdf.id_for_label }}" class="col-sm-2 col-form-label"><strong>PDF</strong></label>
        <div class="col-sm-10">
            {{ form.pdf }}
        </div>
    </div>
    <div class="form-group row my-3">
        <label for="{{ form.video.id_for_label }}" class="col-sm-2 col-form-label"><strong>Video</strong></label>
        <div class="col-sm-10">
            {{ form.video }}
        </div>
    </div>
</form>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    const url = window.location.href
    $(document).ready(() => {
        $.ajax({
            type: 'GET',
            url: `${url}/get-course`,
            success: function(response) {
                const name = response['name'];
                const description = response['description'];
                const body = response['body'];
                $('#id_name').attr('value', name);
                $("#id_description").attr("value", description);
                $("#id_body").text(body);
                tinymce.init({
                    selector: '#id_body'
                });
                console.log(response);
            },
            error: function(response) {
                console.log(response);
            },
        })
    })
</script>
{% endblock %}

templates/teacher/profile.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block profile %}
<div id="teacher-modify">
    <!-- ACCOUNT MODIFY -->
    <form id="account-form" class="mt-2">
        {% csrf_token %}
        <h5 class="text-primary">Cập nhật tài khoản</h5>
        <div class="border-top border-primary mb-3 w-100"></div>
        <div class="row mt-3">
            <label for="usernameMod" class="col-sm-2 col-form-label"><strong>Mã giảng viên</strong></label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control" id="usernameMod" name="usernameMod" value="{{ teacher.teacher.username }}">
            </div>
        </div>
        <div class="row mt-3">
            <label for="passwordMod" class="col-sm-2 col-form-label"><strong>Mật khẩu</strong></label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="passwordMod" name="passwordMod" value="sv123456">
            </div>
        </div>
        <div class="text-end mt-3">
            <span class="text-success" id="notify-account" style="margin-right: 10px;"></span>
            <button type="submit" class="btn btn-success mr-3">Lưu</button>
        </div>
    </form>

    <!-- INFORMATION MODIFY -->
    <form class="mt-5" id="infor-form" enctype="multipart/form-data" method="POST" action="{% url 'teacher_profile' %}">
        {% csrf_token %}
        <h5 class="text-primary">Cập nhật thông tin</h5>
        <div class="border-top border-primary mb-3 w-100"></div>
        <div class="row mt-3">
            <label for="avatarMod" class="col-sm-2 col-form-label"><strong>Ảnh đại diện</strong></label>
            <div class="col-sm-10 text-center">
                <img id="avatarDemo" class="my-3" src="#" alt="avatar" style="height: 100px; width: 100px;border-radius: 50%;">
                <p>{{ form.avatar }}</p>
            </div>
            <script>
                $('document').ready(function () {
                    $("#id_avatar").change(function () {
                        if (this.files && this.files[0]) {
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                $('#avatarDemo').attr('src', e.target.result);
                            }
                            reader.readAsDataURL(this.files[0]);
                        }
                    });
                });
            </script>
        </div>
        <div class="row mt-3">
            <label for="major" class="col-sm-2 col-form-label"><strong>Ngành</strong></label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control" id="major" name="major" value="{{ teacher.major.name }}">
            </div>
        </div>
        <div class="row mt-3">
            <label for="{{ form.name.id_for_label }}" class="col-sm-2 col-form-label"><strong>Họ Tên</strong></label>
            <div class="col-sm-10">
                {{ form.name }}
            </div>
        </div>
        <div class="row mt-3">
            <label for="{{ form.gender.id_for_label }}" class="col-sm-2 col-form-label"><strong>Giới tính</strong></label>
            <div class="col-sm-10">
                {{ form.gender }}
            </div>
        </div>
        <div class="row mt-3">
            <label for="{{ form.email.id_for_label }}" class="col-sm-2 col-form-label"><strong>Email</strong></label>
            <div class="col-sm-10">
                {{ form.email }}
            </div>
        </div>
        <div class="text-end mt-3">
            <span class="mr-3 text-success" id="notify-infor"></span>
            <button type="submit" class="btn btn-success mr-3">Lưu</button>
        </div>
    </form>
</div>
<script src="{% static 'teacher/js/profile.js' %}"></script>
{% endblock %}